# Generated by Django 2.2 on 2021-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
