# Generated by Django 2.2 on 2021-05-15 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address_1',
            field=models.CharField(default=datetime.datetime(2021, 5, 15, 5, 0, 55, 578307, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
    ]
